# suppress inspection "SpellCheckingInspection"
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# suppress inspection "UnusedProperty"
kotlin.code.style=official

# https://blog.jetbrains.com/kotlin/2026/09/a-more-reliable-compilation-scheme-for-kotlin-multiplatform-modules/
# TODO kotlin.kmp.separateCompilation=true
