on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: docker image     build --tag project-image .
      - run: docker container run         project-image ./gradlew markers build
