name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          JAVA_HOME=$JAVA_HOME_11_X64
          chmod +x ./gradlew
          ./gradlew -v
          ./gradlew build
