name: Release
on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      version:
        description: 'Version (MAJOR.MINOR.PATCH)'
        required: true
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v${{ github.event.inputs.version }}
      - name: release
        env: # note: printenv prevents that secrets are visible on command line
          MAVEN_CENTRAL_KEY: ${{ secrets.MAVEN_CENTRAL_KEY }}
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        run: |
          mkdir $HOME/.gradle
          printenv MAVEN_CENTRAL_KEY | base64 -d > $HOME/.gradle/maven.central.key.gpg
          printenv GRADLE_PROPERTIES > $HOME/.gradle/gradle.properties
          echo "signing.secretKeyRingFile=$HOME/.gradle/maven.central.key.gpg" >> $HOME/.gradle/gradle.properties
          JAVA_HOME=$JAVA_HOME_11_X64
          gradle -v
          gradle -Pversion=${{ github.event.inputs.version }} build publishYass2
