#file: noinspection SpellCheckingInspection
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/actions/wrapper-validation@v4
      - name: release
        env: # printenv prevents that secrets are visible on the command line
          MAVEN_CENTRAL_KEY: ${{ secrets.MAVEN_CENTRAL_KEY }}
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        run: |
          printenv MAVEN_CENTRAL_KEY | base64 -d > ~/maven.central.key.gpg
          printenv GRADLE_PROPERTIES             > ~/gradle.properties
          docker image     build                                    --tag project-image .
          docker container create                --name project-container project-image ./gradlew -Pversion=`git describe` markers build publishToMavenCentral
          docker container cp ~/maven.central.key.gpg   project-container:/root/.gradle/maven.central.key.gpg
          docker container cp ~/gradle.properties       project-container:/root/.gradle/gradle.properties
          docker container start --attach --interactive project-container
